### ISSUE TITLE
Update the ampersand symbol to use it's reference

### ISSUE THREAD

**Issue by jim-rosales** [ge8/colmar#3]
Change: `<h5>Tues 10/11 & Wed 10/12: 8am-3pm</h5>`

To: `<h5>Tues 10/11 &amp; Wed 10/12: 8am-3pm</h5>`

When using symbols, it's best to use their entity reference for better compatibility. For example for the copy symbol in your footer you used `&#169;` to reference it

https://github.com/ge8/colmar/blob/63c7c339a637def3ed49c00c64482b37d2525c3b/index.html#L62

**Comment by ge8** [comment]
Done. Thanks
