### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [ge8/colmar#6]
Grade: Exceeds Expectations

Summary:
Gerardo, well done on your capstone project! It shows that you know how to apply CSS efficiently to various sections, know how to structure your files correctly by following industry standards. Apart from all this, you did a thorough job documenting both files which made both files very easy to read and understand what everything did. 

One thing to consider going forward is remembering to use character entity references whenever you are using special symbols in your HTML file. Here is an [article](https://developer.mozilla.org/en-US/docs/Glossary/Entity) that goes more into depth about them and here is [another reference](https://dev.w3.org/html5/html-author/charref) that lists each symbols entity reference. 

For extra practice and as a challenge try adding some [hover effects](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) to your page. They are used widely in the industry so learning how to use them will give you a valuable skill!

**Comment by ge8** [comment]
Thanks @jim-rosales. I've now:
1) Fixed the symbol: https://github.com/ge8/colmar/blob/039abb5ce25a7042c033ec6da7e3b7dac753f121/index.html#L62
2) Added a couple of hover pseudo-class effects: 
https://github.com/ge8/colmar/blob/039abb5ce25a7042c033ec6da7e3b7dac753f121/resources/css/style.css#L54-L56
https://github.com/ge8/colmar/blob/039abb5ce25a7042c033ec6da7e3b7dac753f121/resources/css/style.css#L189-L191
